<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>RS</title>
    <link href="/css/main.css" rel="stylesheet">
</head>
<body class="main-page">

<div class="layout _main">
    <div class="layout__inner _main">
        
        <div class="layout__middle">
            <fieldset class="fieldset">
                <legend>Обновить цены</legend>
                <form action="/api/update_prices" method="post" enctype="multipart/form-data">
                    <input type="file" name="file">
                    <button type="submit">Загрузить</button>
                </form>
            </fieldset>
            
            <fieldset class="fieldset">
                <legend>Обновить приход</legend>
                <form action="/api/recount" method="post" enctype="multipart/form-data">
                    <input type="file" name="file">
                    <button type="submit">Загрузить</button>
                </form>
            </fieldset>
            
            <fieldset class="fieldset">
                <legend>Обновить остатки</legend>
                <form action="/api/remains" method="post" enctype="multipart/form-data">
                    <input type="file" name="file">
                    <button type="submit">Загрузить</button>
                </form>
            </fieldset>
        </div>

    </div>
</div>

</body>
</html>
