<?php require 'partials/_meta.phtml'; ?>

<body class="main-page">

<div class="layout _main">
    <div class="layout__inner _main">
        
        <div class="layout__middle">
            <fieldset class="fieldset">
                <legend>Обновить цены</legend>
                <form action="/api/prices" method="post" enctype="multipart/form-data">
                    <input type="file" name="file">
                    <button type="submit">Загрузить</button>
                </form>
            </fieldset>
            
            <fieldset class="fieldset">
                <legend>Обновить приход</legend>
                <form action="/api/recount" method="post" enctype="multipart/form-data">
                    <input type="file" name="file">
                    <button type="submit">Загрузить</button>
                </form>
            </fieldset>
            
            <fieldset class="fieldset">
                <legend>Обновить остатки</legend>
                <form action="/api/remains" method="post" enctype="multipart/form-data">
                    <input type="file" name="file">
                    <button type="submit">Загрузить</button>
                </form>
            </fieldset>
        </div>

    </div>
</div>

</body>
</html>
