<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>RS</title>
    <link href="/css/main.css" rel="stylesheet">
</head>
<body>

<div class="layout">
    <div class="layout__inner">
        <h1>Update</h1>
        
        <h2>Цены</h2>
        <form action="/api/update_prices" method="post" enctype="multipart/form-data">
            <input type="file" name="file">
            <button type="submit">Загрузить</button>
        </form>

        <h2>Приход</h2>
        <form action="/api/recount" method="post" enctype="multipart/form-data">
            <input type="file" name="file">
            <button type="submit">Загрузить</button>
        </form>

        <h2>Остатки</h2>
        <form action="/api/remains" method="post" enctype="multipart/form-data">
            <input type="file" name="file">
            <button type="submit">Загрузить</button>
        </form>
        
    </div>
</div>

</body>
</html>
