<?php require 'partials/_meta.phtml'; ?>

<body>
    
<div class="layout">
    <?php require 'partials/_navigation.phtml'; ?>
    <div class="layout__inner">
        <?php if (!empty($data)) : ?>
        <form action="/update/prices" method="POST" enctype="multipart/form-data">
            <table class="table" id="table">
                <colgroup>
                    <col width="18">
                    <col>
                    <col width="150">
                    <col width="150">
                    <col width="130">
                </colgroup>
                <thead>
                    <tr>
                        <th><input type="checkbox" class="j-change-all" checked></th>
                        <th>Номенклатура</th>
                        <th>Стоимость</th>
                        <th>Со скидкой</th>
                        <th>Статус</th>
                    </tr>
                </thead>
                <?php foreach ($data as $row) : ?>
                <tr>
                    <td><input type="checkbox" name="change[<?=$row['number'];?>]" value="<?=$row['number'];?>" class="j-change-item" checked></td>
                    <td>
                        <span class="clipboard j-clipboard" data-clipboard="<?php echo $row['name']; ?>">
                            <span class="clipboard__text"><?php echo $row['name']; ?></span>
                        </span>
                    </td>
                    <td>
                        <span class="price j-clipboard" data-clipboard="<?php echo $row['price']; ?>">
                            <span class="price__text">
                                <?php echo $row['price']; ?>
                            </span>
                        </span>
                    </td>
                    <td>
                        <?php if (isset($_SESSION['update']['prices'][$row['number']]['discount_price'])): ?>
                            <?php echo $_SESSION['update']['prices'][$row['number']]['discount_price']; ?>
                        <?php endif; ?>
                    </td>
                    <td class="_tac">
                        <?php if (isset($_SESSION['update']['prices']) && isset($_SESSION['update']['prices'][$row['number']])): ?>
                            <?php if ($_SESSION['update']['prices'][$row['number']]['status'] == 1): ?>
                                <i class="status _success"></i>
                            <?php else: ?>
                                <i class="status _fail"></i>
                            <?php endif; ?>

                            <?php if ($_SESSION['update']['prices'][$row['number']]['id']): ?>
                                <a href="<?php echo $_SESSION['update']['prices'][$row['number']]['link']; ?>" class="link _check" target="_blank">Проверить</a>
                            <?php else: ?>
                                <a href="#" class="link _add">Добавить</a>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </table>

            <div class="form__row">
                <input name="discount" value="0">
            </div>

            <button class="submit" type="submit">Обновить</button>
        </form>
        <?php endif; ?>
    </div>
</div>

<script src="/js/jquery.min.js"></script>
<script src="/js/clipboard.min.js"></script>
<script src="/js/functions.js"></script>
<script src="/js/app.js"></script>
</body>
</html>
