<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Update page</title>
    <link href="/css/main.css" rel="stylesheet">
</head>
<body>

<div class="layout">
    <div class="layout__inner">
        <?php if (!empty($data)) : ?>
        <form action="/update/recount" method="POST" enctype="multipart/form-data">
            <table class="table" id="table">
                <colgroup>
                    <col width="18">
                    <col>
                    <col width="100">
                    <col width="120">
                </colgroup>
                <thead>
                    <tr>
                        <th><input type="checkbox" name="changeall" class="j-change-all"></th>
                        <th>Номенклатура</th>
                        <th>Код</th>
                        <th>Кол-во</th>
                        <th>Стоимость</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $key => $row) : ?>
                <tr>
                    <td><input type="checkbox" name="site[<?=$key;?>]" class="j-change-item"></td>
                    <td>
                        <span class="clipboard j-clipboard" data-clipboard="<?php echo $row['name']; ?>">
                            <span class="clipboard__text"><?php echo $row['name']; ?></span>
                        </span>
                    </td>
                    <td>
                        <span class="clipboard j-clipboard" data-clipboard="<?php echo $row['code']; ?>">
                            <span class="clipboard__text"><?php echo $row['code']; ?></span>
                        </span>
                    </td>
                    <td>
                        <span class="price j-clipboard" data-clipboard="<?php echo $row['count']; ?>">
                            <span class="price__text">
                                <?php echo $row['count']; ?>
                            </span>
                        </span>
                    </td>
                    <td>
                        <span class="price j-clipboard" data-clipboard="<?php echo $row['price']; ?>">
                            <span class="price__text">
                                <?php echo $row['price']; ?>
                            </span>
                        </span>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <button class="submit" type="submit">Обновить</button>
        </form>
        <?php endif; ?>
    </div>
</div>

<script src="/js/jquery.min.js"></script>
<script src="/js/clipboard.min.js"></script>
<script src="/js/functions.js"></script>
<script src="/js/app.js"></script>
</body>
</html>