<?php require 'partials/_meta.phtml'; ?>

<body>
    
<div class="layout">
    <?php require 'partials/_navigation.phtml'; ?>
    <div class="layout__inner">
        <?php if (!empty($data)) : ?>
        <form action="/update/remains" method="POST" enctype="multipart/form-data">
            <table class="table" id="table">
                <colgroup>
                    <col width="18">
                    <col>
                    <col width="190">
                    <col width="120">
                    <col width="120">
                    <col width="120">
                </colgroup>
                <thead>
                    <tr>
                        <th><input type="checkbox" class="j-change-all" checked></th>
                        <th>Номенклатура</th>
                        <!--
                        <th>Начальный остаток</th>
                        <th>Приход</th>
                        <th>Расход</th>
                        -->
                        <th>Остаток</th>
                    </tr>
                </thead>

                <?php foreach ($data as $row) : ?>
                <tr>
                    <td>    
                        <input type="checkbox" name="change[<?=$row['number'];?>]" value="<?=$row['number'];?>" class="j-change-item" checked>
                    </td>
                    <td>
                        <span class="clipboard j-clipboard" data-clipboard="<?php echo $row['name']; ?>">
                            <span class="clipboard__text"><?php echo $row['name']; ?></span>
                        </span>
                    </td>
                    <!--
                    <td>
                        <span class="price j-clipboard" data-clipboard="<?php echo $row['opening']; ?>">
                            <span class="price__text">
                                <?php echo round($row['opening'], 0); ?>
                            </span>
                        </span>
                    </td>
                    <td>
                        <span class="price j-clipboard" data-clipboard="<?php echo $row['parish']; ?>">
                            <span class="price__text">
                                <?php echo round($row['parish'], 0); ?>
                            </span>
                        </span>
                    </td>
                    <td>
                        <span class="price j-clipboard" data-clipboard="<?php echo $row['consumption']; ?>">
                            <span class="price__text">
                                <?php echo round($row['consumption'], 0); ?>
                            </span>
                        </span>
                    </td>
                    -->
                    <td>
                        <span class="price j-clipboard" data-clipboard="<?php echo $row['balance']; ?>">
                            <span class="price__text">
                                <?php echo round($row['balance'], 0); ?>
                            </span>
                        </span>
                    </td>
                    <!-- 
                    <td>
                        <div class="upload j-upload">
                            <label class="upload__form j-upload-form">
                                <span class="upload__title">Загрузить</span>
                                <input name="file[<?php echo $row['number']; ?>]" type="file" class="upload__input j-upload-input" multiple>
                            </label>
                            
                            <span class="upload__list j-upload-list"></span>
                        </div>
                    </td>
                    -->
                </tr>
                <?php endforeach; ?>
            </table>

            <div class="form__row">
                <input name="discount" value="0">
            </div>

            <button class="submit" type="submit">Обновить</button>
        </form>
        <?php endif; ?>
    </div>
</div>

<script src="/js/jquery.min.js"></script>
<script src="/js/clipboard.min.js"></script>
<script src="/js/functions.js"></script>
<script src="/js/app.js"></script>
</body>
</html>
