<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Update page</title>
    <link href="/css/main.css" rel="stylesheet">
</head>
<body>
    
<div class="layout">
    <div class="layout__inner">
        <?php if (!empty($data)) : ?>
        <form action="/update/update_prices" method="POST" enctype="multipart/form-data">
            <table class="table" id="table">
                <colgroup>
                    <col width="18">
                    <col>
                    <col width="190">
                    <col width="120">
                    <col width="120">
                    <col width="120">
                </colgroup>
                <thead>
                    <tr>
                        <th><input type="checkbox" name="changeall" class="j-change-all" checked></th>
                        <th>Номенклатура</th>
                        <th>Начальный остаток</th>
                        <th>Приход</th>
                        <th>Расход</th>
                        <th>Остаток</th>
                    </tr>
                </thead>

                <?php foreach ($data as $key => $row) : ?>
                <tr>
                    <td><input type="checkbox" name="site[<?=$key;?>]" class="j-change-item" checked></td>
                    <td>
                        <span class="clipboard j-clipboard" data-clipboard="<?php echo $row['name']; ?>">
                            <span class="clipboard__text"><?php echo $row['name']; ?></span>
                        </span>
                    </td>
                    <td>
                        <span class="price j-clipboard" data-clipboard="<?php echo $row['opening']; ?>">
                            <span class="price__text">
                                <?php echo round($row['opening'], 0); ?>
                            </span>
                        </span>
                    </td>
                    <td>
                        <span class="price j-clipboard" data-clipboard="<?php echo $row['parish']; ?>">
                            <span class="price__text">
                                <?php echo round($row['parish'], 0); ?>
                            </span>
                        </span>
                    </td>
                    <td>
                        <span class="price j-clipboard" data-clipboard="<?php echo $row['consumption']; ?>">
                            <span class="price__text">
                                <?php echo round($row['consumption'], 0); ?>
                            </span>
                        </span>
                    </td>
                    <td>
                        <span class="price j-clipboard" data-clipboard="<?php echo $row['balance']; ?>">
                            <span class="price__text">
                                <?php echo round($row['balance'], 0); ?>
                            </span>
                        </span>
                    </td>
                </tr>
                <?php endforeach; ?>
            </table>

            <button class="submit" type="submit">Обновить</button>
        </form>
        <?php endif; ?>
    </div>
</div>

<script src="/js/jquery.min.js"></script>
<script src="/js/clipboard.min.js"></script>
<script src="/js/functions.js"></script>
<script src="/js/app.js"></script>
</body>
</html>
