<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Update page</title>
    <link href="/css/main.css" rel="stylesheet">
</head>
<body>
    
<div class="layout">
    <?php require 'navigation.phtml'; ?>
    <div class="layout__inner">
        <?php if (!empty($data)) : ?>
        <form action="/update/update_prices" method="POST" enctype="multipart/form-data">
            <table class="table" id="table">
                <colgroup>
                    <col width="18">
                    <col>
                    <col width="150">
                </colgroup>
                <thead>
                    <tr>
                        <th><input type="checkbox" class="j-change-all"></th>
                        <th>Номенклатура</th>
                        <th>Стоимость</th>
                        <!-- <th>Фото</th> -->
                    </tr>
                </thead>
                <?php foreach ($data as $key => $row) : ?>
                <tr>
                    <td><input type="checkbox" name="site[<?=$key;?>]" class="j-change-item"></td>
                    <td>
                        <span class="clipboard j-clipboard" data-clipboard="<?php echo $row['name']; ?>">
                            <span class="clipboard__text"><?php echo $row['name']; ?></span>
                        </span>
                    </td>
                    <td>
                        <span class="price j-clipboard" data-clipboard="<?php echo $row['price']; ?>">
                            <span class="price__text">
                                <?php echo $row['price']; ?>
                            </span>
                        </span>
                    </td>
                    <!-- 
                    <td>
                        <div class="upload j-upload">
                            <label class="upload__form j-upload-form">
                                <span class="upload__title">Загрузить</span>
                                <input name="file[<?php echo $row['number']; ?>]" type="file" class="upload__input j-upload-input" multiple>
                            </label>
                            
                            <span class="upload__list j-upload-list"></span>
                        </div>
                    </td>
                    -->
                </tr>
                <?php endforeach; ?>
            </table>

            <div class="form__row">
                <input name="discount" value="0">
            </div>

            <button class="submit" type="submit">Обновить</button>
        </form>
        <?php endif; ?>
    </div>
</div>

<script src="/js/jquery.min.js"></script>
<script src="/js/clipboard.min.js"></script>
<script src="/js/functions.js"></script>
<script src="/js/app.js"></script>
</body>
</html>
